#pragma once
#ifndef INCLUDED_BLOCK_CATEGORY_H_
#define INCLUDED_BLOCK_CATEGORY_H_

enum BlockCategory {
	TYPE_L, 
	TYPE_L_REVERSE, 
	TYPE_T, 
	TYPE_S, 
	TYPE_S_REVERSE, 
	TYPE_O, 
	TYPE_I
};

#endif // !INCLUDED_BLOCK_CATEGORY_H_
